// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBABTiZQt_I-TCHLWmpntC4LyXhF_pFawQ',
    appId: '1:741037305385:web:ea94daa90db84f9be63638',
    messagingSenderId: '741037305385',
    projectId: 'astro-2210b',
    authDomain: 'astro-2210b.firebaseapp.com',
    storageBucket: 'astro-2210b.firebasestorage.app',
    measurementId: 'G-0ZL266SQ5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdmAtLTrHw23hVak6gwyQZPK7sSdNKgE',
    appId: '1:741037305385:android:57180e7c2d392f0ce63638',
    messagingSenderId: '741037305385',
    projectId: 'astro-2210b',
    storageBucket: 'astro-2210b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHvSziYkRCRkgEyiM0VCL-QsbYLqhsAC4',
    appId: '1:741037305385:ios:3448aea703ea13f8e63638',
    messagingSenderId: '741037305385',
    projectId: 'astro-2210b',
    storageBucket: 'astro-2210b.firebasestorage.app',
    iosBundleId: 'com.astrosarthikonnectastrologerapp.astrosarthiKonnectAstrologerApp',
  );
}
